version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: MongoDB_CSU33012_API
    environment:
      - PUID=1000
      - PGID=1000
      # volumes:
      # - /somedirectory:/data/db  # you need to modify this
    ports:
      - 27017:27017
    restart: unless-stopped
